version: '3.7'


# Subir toda a stack
# docker-compose up

# Derrubar a stack 
# docker-compose down
# docker-compose down -v (destruindo os volumes)

# Recompilar imagems locais (no caso app) (fazer isso quando tiver nova versão do JAR)
# docker-compose build --no-cache


services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    restart: always
    
   
